services:
  zookeeper:
    extends:
      file: "docker-compose/base/docker-compose.kafka.yml"
      service: zookeeper

  kafka1:
    extends:
      file: "docker-compose/base/docker-compose.kafka.yml"
      service: kafka1
    depends_on:
      zookeeper:
        condition: service_healthy

  kafka2:
    extends:
      file: "docker-compose/base/docker-compose.kafka.yml"
      service: kafka2
    depends_on:
      zookeeper:
        condition: service_healthy


  kafka3:
    extends:
      file: "docker-compose/base/docker-compose.kafka.yml"
      service: kafka3
    depends_on:
      zookeeper:
        condition: service_healthy
  clickhouse-server:
    extends:
      file: "docker-compose/base/docker-compose.clickhouse.yml"
      service: clickhouse-server

  grafana:
    extends:
      file: "docker-compose/base/docker-compose.grafana.yml"
      service: grafana

  prometheus:
    extends:
      file: "docker-compose/base/docker-compose.prometheus.yml"
      service: prometheus

  kafka-exporter:
    extends:
      file: "docker-compose/base/docker-compose.kafka-exporter.yml"
      service: kafka-exporter
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
  zeek1:
    image: ghcr.io/hamstring-ndr/hamstring-zeek:v1.0.0
    environment:
      - CONTAINER_NAME=zeek1
    volumes:
      - ../data/test_pcaps/:/opt/static_files
      - ../../../config.yaml:/opt/config.yaml
    cap_add:
      - NET_ADMIN
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
      grafana:
        condition: service_healthy
    network_mode: host

  monitoring_agent-dev:
    extends:
      file: "docker-compose/dev/docker-compose.monitoring.yml"
      service: monitoring_agent
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
    profiles: ["dev"]

  monitoring_agent:
    extends:
      file: "docker-compose/prod/docker-compose.monitoring.yml"
      service: monitoring_agent
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
    profiles: ["prod"]

  logserver-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: logserver
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["dev"]

  logserver:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: logserver
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["prod"]

  logcollector-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: logcollector
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["dev"]


  logcollector:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: logcollector
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["prod"]

  prefilter-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: prefilter
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["dev"]

  prefilter:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: prefilter
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["prod"]

  inspector-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: inspector
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["dev"]

  inspector:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: inspector
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["prod"]


  detector-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: detector
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["dev"]

  detector:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: detector
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["prod"]

  alerter-dev:
    extends:
      file: "docker-compose/dev/docker-compose.pipeline.yml"
      service: alerter
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["dev"]

  alerter:
    extends:
      file: "docker-compose/prod/docker-compose.pipeline.yml"
      service: alerter
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    profiles: ["prod"]

networks:
  hamstring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1

volumes:
  ch_data:
  ch_logs:
  kafka-data1:
  kafka-data2:
  kafka-data3:
  zk-data:
  zk-txn-logs:
