services:
  logserver:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.logserver
    volumes:
      - "${MOUNT_PATH:?MOUNT_PATH not set}:/opt/file.txt"
      - ../../../config.yaml:/app/config.yaml
    environment:
      - GROUP_ID=log_storage
    networks:
      heidgaf:
      
  logcollector:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.logcollector
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      heidgaf:
    environment:
      - GROUP_ID=log_collection
  prefilter:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.prefilter
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      heidgaf:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=log_filtering
  inspector:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.inspector
      network: host
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      heidgaf:
    deploy:
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 512m
        reservations:
          cpus: '1'
          memory: 256m
    environment:
      - GROUP_ID=data_inspection
      - NUMBER_OF_INSTANCES=1
  detector:
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/Dockerfile.detector
    restart: "unless-stopped"
    volumes:
      - ../../../config.yaml:/app/config.yaml
    networks:
      heidgaf:
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      - GROUP_ID=data_analysis

